baseURL = "https://gardener.cloud/"
title = "Gardener"
theme = "docsy"
metaDataFormat = "yaml"
languageCode = "en-US"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir= true
contentDir="content"
enableGitInfo = true
# Google Analytics Track ID
googleAnalytics = "UA-165447164-1"
disableHugoGeneratorInject = true

[menu]
  [[menu.main]]
      name = "Blog"
      weight = 40
      url = "/blog"
  [[menu.main]]
      name = "Community"
      weight = 40
      url = "/community"
  [[menu.main]]
      name = "Adopters"
      weight = 40
      url = "/adopters"
  [[menu.main]]
      name = "Documentation"
      weight = 40
      url = "/docs"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    guessSyntax = true
    noClasses = false
    style = "vs"
    tabWidth = 4

[params]
  github_repo = "https://github.com/google/docsy"
  defaultURL = "https://github.com/kubernetes/documentation/tree/master/website/"
  editURL = "https://github.com/gardener/documentation/edit/master/website/"
  issueURL = "https://github.com/gardener/documentation/issues"
  copyright = "Copyright 2019-2021 Gardener project authors."
  privacyPolicyURL = "https://www.sap.com/corporate/en/legal/privacy.html"
  description = "Project Gardener Website - A Managed Kubernetes Service Done Right"
  # Google Tag Manager container
  googleTagsManager = "GTM-W2FGNSX"
  # Google Search Console site verification tag
  googleSiteVerificationTag = "9EoGiMwk2aq0E_tVh16iJgJbp7fbyqkfWH9b5sGybl0"
  [params.pageTopBar]
    display = true
    displayContributors = true
    displayLastUpdate = true
    displayEdit = true
    displayOriginURL = false
  [params.links]


[outputs]
home = [ "HTML", "RSS" ]

# Docsy: User interface configuration
[params.ui]
# Docsy: Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
# Docsy: Disable the search box in the side bar.
sidebar_search_disable = false
#  Docsy: Set to true to disable breadcrumb navigation.
breadcrumb_disable = true
navbar_logo = true

