services:
  hugo-website:
    image: testing-website-image
    environment:
      HUGO_FLAGS: "--bind=0.0.0.0"
    ports:
    - 1313:1313
    volumes:
    - ./hugo:/hugo 
    secrets:
    - docforge_config
secrets:
  docforge_config:
    file: ./docforge_config.yaml